# Generated by Django 4.1.5 on 2023-01-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='firm_name',
            field=models.CharField(default='TUIT', max_length=250),
            preserve_default=False,
        ),
    ]
