# Generated by Django 4.1.5 on 2023-01-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_application_firm_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('BK', 'Bachelor'), ('MS', 'Master'), ('DK', 'Doctor')], default='BK', max_length=2)),
                ('cont_amount', models.IntegerField()),
                ('otm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.university')),
            ],
            options={
                'ordering': ['-cont_amount'],
            },
        ),
    ]
