# Generated by Django 4.1.5 on 2023-01-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_university_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_num',
            field=models.IntegerField(default=12000000),
            preserve_default=False,
        ),
    ]
