# Generated by Django 4.1.5 on 2023-01-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sponsorship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
