# Generated by Django 4.1.5 on 2023-01-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sponsorship_options_alter_student_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorShip',
        ),
    ]
