# Generated by Django 4.1.5 on 2023-01-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sponsorship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='student',
        ),
    ]
