# Generated by Django 4.1.5 on 2023-01-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_sponsorship_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='application',
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
