# Generated by Django 4.1.5 on 2023-01-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_sponsorship_application_sponsorship_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.application'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
            preserve_default=False,
        ),
    ]
