# Generated by Django 4.1.5 on 2023-01-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sponsorship_application_alter_sponsorship_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship', to='api.application'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship', to='api.student'),
        ),
    ]
