# Generated by Django 4.1.5 on 2023-01-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_sponsorship_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_num',
            field=models.CharField(max_length=13),
        ),
    ]
