# Generated by Django 4.1.5 on 2023-01-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_student_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.IntegerField()),
                ('required_amount', models.IntegerField()),
                ('asked_amount', models.IntegerField()),
            ],
        ),
    ]
